name: Repository Events
on:
    push:
        branches:
            - main
            - "feature/*"  #workflow syntax
            - "!feature/fitA"
        #branches-ignore:
        #    - develop    
        tags:
            - v1.*
            - "!v1.1"
        paths:  
            - "**.js"
            - "!app.js"
    pull_request:
        types: [opened, reopened]
    issues:
        types: [opened]        

jobs:
    chekout-test:
        runs-on: ubuntu-latest
        steps :
            - run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - uses: actions/checkout@v4    
