name: First Workflow
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps: 
            - name: echo a string
              run: echo "Hello World"
            - name: Multiline Commands
              run: |
                node -v
                npm -v
            #- name: log string from JS code
            #  run: node hello.js  
    parallel-job-macos:
        runs-on: macos-latest
        steps:
            - name: View SW Version
              run: sw_vers
    depended-job:
        runs-on: windows-latest
        needs: run-shell-commands
        steps:
             - name: echo a string
               run: Write-Output "Windows String"
             - name: Error Step
               run: something 


