name: First Workflow
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps: 
            - name: echo a string
              run: echo "Hello World"
            - name: Multiline Commands
              run: |
                node -v
                npm -v
            - name: log string from JS code
              run: node hello.js  
