name: Workflow Run
on:
    workflow_run:
        workflows: [Repository Events]
        types: [completed]

jobs:
    echo_simple:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Repository Events was completed"